worldName: example-world-name
serverName: example-server-name
password: password 

resources: {}

storage:
  kind: hostvol
  hostvol:
    path: /data/valheim
  nfs:
    path:
    server:

networking:
  serviceType: LoadBalancer
  loadBalancerIP:

nodeSelector: {}
